#!/usr/bin/env bash
# Upload file to the server
msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";

if [ $# -lt 3 ];
then
	echo $msg;
	exit;
fi;
if [ $# -ge 4 ];
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2";~/
else
	scp -o StrictHostKeyChecking=no -i "$4" "$3"@"$2";~/
fi;
